CREATE TABLE transactions (
    transaction_id      INT,
    trans_date_trans_time TIMESTAMP,
    cc_num              BIGINT,
    merchant            TEXT,
    category            TEXT,
    amt                 NUMERIC(10,2),
    first               TEXT,
    last                TEXT,
    gender              CHAR(1),
    street              TEXT,
    city                TEXT,
    state               CHAR(2),
    zip                 INT,
    lat                 NUMERIC(9,6),
    long                NUMERIC(9,6),
    city_pop            INT,
    job                 TEXT,
    dob                 DATE,
    trans_num           TEXT,
    unix_time           BIGINT,
    merch_lat           NUMERIC(9,6),
    merch_long          NUMERIC(9,6),
    is_fraud            INT,
    merch_zipcode       INT,
    status              TEXT
);
